[35mDEBUG   [0m root:conftest.py:18 üë§ Criando novo usu√°rio para o teste: usuario_teste_8802
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/Authorized HTTP/1.1" 200 4
[35mDEBUG   [0m root:conftest.py:36 ‚úÖ Usu√°rio criado e autorizado com sucesso. ID: a2613f9e-da47-4c77-94fa-6f13dca9d5f6, Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfODgwMiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzcyOTc4fQ.0klusFMRsW1b51RffWzvjWBOgDpgmSSJsOy6dcVuyC8
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_given_que eu tenho um usu√°rio criado e autenticado': [<FixtureDef argname='pytestbdd_stepdef_given_que eu tenho um usu√°rio criado e autenticado' scope='function' baseid='tests/api/test_user_details.py'>]
[32mINFO    [0m root:test_user_details.py:21 üü¢ [IN√çCIO] Criando e autenticando usu√°rio para consulta de detalhes
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[32mINFO    [0m root:test_user_details.py:34 ‚úÖ Usu√°rio criado com sucesso! ID: 04327729-8b93-4e69-a36a-c81ca8958bdb
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[32mINFO    [0m root:test_user_details.py:58 üîë Token gerado com sucesso: eyJhbGciOiJIUzI1NiIs...
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_when_eu envio uma requisi√ß√£o para obter os detalhes do usu√°rio': [<FixtureDef argname='pytestbdd_stepdef_when_eu envio uma requisi√ß√£o para obter os detalhes do usu√°rio' scope='function' baseid='tests/api/test_user_details.py'>]
[32mINFO    [0m root:test_user_details.py:63 üîç Solicitando detalhes do usu√°rio...
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "GET /Account/v1/User/04327729-8b93-4e69-a36a-c81ca8958bdb HTTP/1.1" 200 92
[35mDEBUG   [0m root:api_client.py:35 üì• Resposta da API ao obter detalhes do usu√°rio: 200 - {"userId":"04327729-8b93-4e69-a36a-c81ca8958bdb","username":"usuario_teste_6660","books":[]}
[32mINFO    [0m root:test_user_details.py:68 üì§ Resposta recebida da API (200):
{
    "userId": "04327729-8b93-4e69-a36a-c81ca8958bdb",
    "username": "usuario_teste_6660",
    "books": []
}
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_then_a API deve retornar os detalhes corretos do usu√°rio': [<FixtureDef argname='pytestbdd_stepdef_then_a API deve retornar os detalhes corretos do usu√°rio' scope='function' baseid='tests/api/test_user_details.py'>]
[32mINFO    [0m root:test_user_details.py:73 ‚úÖ Validando resposta da API para detalhes do usu√°rio...
[32mINFO    [0m root:test_user_details.py:81 ‚úÖ Os detalhes do usu√°rio est√£o corretos!