[35mDEBUG   [0m root:conftest.py:14 üë§ Criando usu√°rio de teste: usuario_teste_7444
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m root:api_client.py:20 üì§ Gerando token para usu√°rio: usuario_teste_7444
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m root:api_client.py:24 üì• Resposta da API ao gerar token: 200 - {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzQ0NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4OTQ0fQ.Yc3opBHefet1u8iE4z3J2zDaRWxzoqRBrHzj6Hpj6K8","expires":"2025-02-19T14:02:24.719Z","status":"Success","result":"User authorized successfully."}
[35mDEBUG   [0m root:api_client.py:29 ‚úÖ Token gerado com sucesso: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzQ0NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4OTQ0fQ.Yc3opBHefet1u8iE4z3J2zDaRWxzoqRBrHzj6Hpj6K8
[35mDEBUG   [0m root:api_client.py:68 üì§ Realizando login para usu√°rio: usuario_teste_7444
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/Login HTTP/1.1" 200 390
[35mDEBUG   [0m root:api_client.py:72 üì• Resposta da API ao tentar login: 200 - {"userId":"5c496070-fe62-4190-a41f-686532b7284d","username":"usuario_teste_7444","password":"Teste@123","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzQ0NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4OTQ0fQ.Yc3opBHefet1u8iE4z3J2zDaRWxzoqRBrHzj6Hpj6K8","expires":"2025-02-19T14:02:24.000Z","created_date":"2025-02-12T14:02:24.000Z","isActive":false}
[35mDEBUG   [0m root:conftest.py:39 ‚úÖ Login realizado com sucesso para o usu√°rio: usuario_teste_7444
[35mDEBUG   [0m root:conftest.py:41 ‚úÖ Usu√°rio criado e autorizado com sucesso. ID: 5c496070-fe62-4190-a41f-686532b7284d, Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzQ0NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4OTQ0fQ.Yc3opBHefet1u8iE4z3J2zDaRWxzoqRBrHzj6Hpj6K8
[35mDEBUG   [0m root:conftest.py:48 üîç Antes do teste: Token Atual = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzQ0NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4OTQ0fQ.Yc3opBHefet1u8iE4z3J2zDaRWxzoqRBrHzj6Hpj6K8
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_given_que eu tenho um usu√°rio criado': [<FixtureDef argname='pytestbdd_stepdef_given_que eu tenho um usu√°rio criado' scope='function' baseid='tests/api/test_auth.py'>]
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_when_envio uma requisi√ß√£o para autenticar o usu√°rio': [<FixtureDef argname='pytestbdd_stepdef_when_envio uma requisi√ß√£o para autenticar o usu√°rio' scope='function' baseid='tests/api/test_auth.py'>]
[35mDEBUG   [0m root:api_client.py:20 üì§ Gerando token para usu√°rio: usuario_teste_9276
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m root:api_client.py:24 üì• Resposta da API ao gerar token: 200 - {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfOTI3NiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4OTQ2fQ.mEZcQ5e0b3mfwDm-UNlD2EyldlnB87ndEI7Y9JD6pfs","expires":"2025-02-19T14:02:26.808Z","status":"Success","result":"User authorized successfully."}
[35mDEBUG   [0m root:api_client.py:29 ‚úÖ Token gerado com sucesso: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfOTI3NiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4OTQ2fQ.mEZcQ5e0b3mfwDm-UNlD2EyldlnB87ndEI7Y9JD6pfs
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_then_a API deve retornar um token de autentica√ß√£o': [<FixtureDef argname='pytestbdd_stepdef_then_a API deve retornar um token de autentica√ß√£o' scope='function' baseid='tests/api/test_auth.py'>]