{"uuid": "ca661eca-6bf2-4d8a-895e-15bf42a1496d", "children": ["2edadbc3-1291-417a-ba34-d8a8e3430229", "e83f3e05-aa1d-4433-97f4-eabf103fb80f", "28fe9adc-595d-4380-878c-95b3f6d1e147", "e572d630-d2a2-404c-967f-373d99b116af"], "befores": [{"name": "setup_user", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'APIClient' has no attribute 'login'\n", "trace": "  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/conftest.py\", line 37, in setup_user\n    login_response = APIClient.login(pytest.user_name, pytest.password)\n                     ^^^^^^^^^^^^^^^\n"}, "start": 1739368666041, "stop": 1739368667737}], "start": 1739368666041, "stop": 1739368667782}