[35mDEBUG   [0m root:conftest.py:18 üë§ Criando novo usu√°rio para o teste: usuario_teste_5044
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/Authorized HTTP/1.1" 200 4
[35mDEBUG   [0m root:conftest.py:36 ‚úÖ Usu√°rio criado e autorizado com sucesso. ID: 60434d2e-ea2c-478a-baed-21bcd496698c, Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNTA0NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzcwODY2fQ.AV7o0uU7BeSyWzfzrjpMEOdYU5oqcViQrsR5xxux960
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_given_que eu tenho um nome de usu√°rio e uma senha v√°lidos': [<FixtureDef argname='pytestbdd_stepdef_given_que eu tenho um nome de usu√°rio e uma senha v√°lidos' scope='function' baseid='tests/api/test_create_user.py'>]
[32mINFO    [0m root:test_create_user.py:20 üü¢ [IN√çCIO] Gerando Usu√°rio para Teste