{"name": "test_criar_um_usu치rio_com_credenciais_v치lidas", "status": "failed", "statusDetails": {"message": "AssertionError: Erro ao criar usu치rio: {\"code\":\"1204\",\"message\":\"User exists!\"}\nassert 406 == 201\n +  where 406 = <Response [406]>.status_code", "trace": "@pytest.fixture(scope=\"function\", autouse=True)\n    def setup_user():\n        \"\"\"Cria um novo usu치rio para cada teste e gera um novo token\"\"\"\n        user_data = {\n            \"userName\": generate_username(),\n            \"password\": get_default_password()\n        }\n        logging.debug(f\"游녻 Criando novo usu치rio para o teste: {user_data['userName']}\")\n    \n        response = APIClient.create_user(user_data[\"userName\"], user_data[\"password\"])\n>       assert response.status_code == 201, f\"Erro ao criar usu치rio: {response.text}\"\nE       AssertionError: Erro ao criar usu치rio: {\"code\":\"1204\",\"message\":\"User exists!\"}\nE       assert 406 == 201\nE        +  where 406 = <Response [406]>.status_code\n\nconftest.py:21: AssertionError"}, "description": "/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/features/api_create_user.feature: Criar um usu치rio com credenciais v치lidas", "attachments": [{"name": "log", "source": "7d5a557f-0a66-4b50-ac2f-9f86a76b9bb0-attachment.txt", "type": "text/plain"}], "start": 1739371022448, "stop": 1739371022448, "uuid": "568f10b6-123c-4a72-a40a-efd54b190404", "historyId": "a7574963e73b147341298284211deff8", "testCaseId": "a7574963e73b147341298284211deff8", "fullName": "tests.api.test_create_user#test_criar_um_usu치rio_com_credenciais_v치lidas", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_create_user"}, {"name": "host", "value": "MacBook-Pro-de-Danilo.local"}, {"name": "thread", "value": "51270-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_create_user"}]}